### ISSUE TITLE
joinPath() not working

### ISSUE THREAD

**Issue by Prior99** [Rantanen/node-mumble#14]
It throws an exception:

	/home/prior/Projects/mumble-bot/node_modules/mumble/lib/MumbleConnection.js:163
	        var nextChannel = this._findChannel( channel.channelId, segment, true
	                                                    ^
	TypeError: Cannot read property 'channelId' of undefined
	    at EventEmitter.MumbleConnection.joinPath (/home/prior/Projects/mumble-bot/node_modules/mumble/lib/MumbleConnection.js:163:53)
	    at EventEmitter.MumbleWrapper.joinPath (/home/prior/Projects/mumble-bot/node_modules/mumble/lib/MumbleWrapper.js:226:28)
	    at Connection.join (/home/prior/Projects/mumble-bot/src/connection.js:17:15)
	    at startup (/home/prior/Projects/mumble-bot/index.js:26:4)
	    at /home/prior/Projects/mumble-bot/index.js:20:3
	    at TLSSocket.<anonymous> (/home/prior/Projects/mumble-bot/node_modules/mumble/index.js:41:9)
	    at TLSSocket.g (events.js:199:16)
	    at TLSSocket.emit (events.js:104:17)
	    at TLSSocket.<anonymous> (_tls_wrap.js:946:18)
	    at TLSSocket.emit (events.js:104:17)

**Comment by Prior99** [comment]
My bad. I forgot to initialize.
