### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Prior99** [Rantanen/node-mumble#20]
/home/music/mumble-bot/node_modules/mumble/lib/MumbleWrapper.js:90
        user._detach()
            ^
TypeError: Cannot read property '_detach' of undefined
    at EventEmitter.MumbleWrapper._userRemove (/home/music/mumble-bot/node_modules/mumble/lib/MumbleWrapper.js:90:13)
    at EventEmitter.emit (events.js:107:17)
    at EventEmitter.MumbleConnection._processMessage (/home/music/mumble-bot/node_modules/mumble/lib/MumbleConnection.js:403:10)
    at EventEmitter.MumbleConnection._processData (/home/music/mumble-bot/node_modules/mumble/lib/MumbleConnection.js:358:14)
    at Object.callback (/home/music/mumble-bot/node_modules/mumble/lib/MumbleConnection.js:804:18)
    at MumbleSocket._checkReader (/home/music/mumble-bot/node_modules/mumble/lib/MumbleSocket.js:125:12)
    at MumbleSocket.read (/home/music/mumble-bot/node_modules/mumble/lib/MumbleSocket.js:55:43)
    at Object.callback (/home/music/mumble-bot/node_modules/mumble/lib/MumbleConnection.js:803:21)
    at MumbleSocket._checkReader (/home/music/mumble-bot/node_modules/mumble/lib/MumbleSocket.js:125:12)
    at MumbleSocket.receiveData (/home/music/mumble-bot/node_modules/mumble/lib/MumbleSocket.js:39:10)
    at TLSSocket.<anonymous> (/home/music/mumble-bot/node_modules/mumble/lib/MumbleSocket.js:22:14)

**Comment by Rantanen** [comment]
Can take a look at this issue tomorrow. Today will be full of barbecue. :)
